name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or 'main' if you're using that

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Make sure your index.html is at root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
